DROP DATABASE IF EXISTS uniwa;
CREATE DATABASE uniwa;
USE uniwa;

CREATE TABLE CLASS
(
    COURSE VARCHAR(200) NOT NULL,
    CLASS_ID VARCHAR(20) NOT NULL,
    SEMESTER INT NOT NULL,
    PERIOD CHAR(1) NOT NULL,
    ECTS INT,
    UNITS INT,
    HOURS INT,
    ORIENTATION VARCHAR(5),
    COURSE_TYPE VARCHAR(20),
    PRIMARY KEY(CLASS_ID)
);

CREATE TABLE STUDENT 
(
    STUDENT_ID VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    SEMESTER INT,
    PRIMARY KEY(STUDENT_ID)
);

CREATE TABLE GRADE 
(
    GRADE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID VARCHAR(20) NOT NULL,
    CLASS_ID VARCHAR(20) NOT NULL,
    GRADE FLOAT DEFAULT 5,
    PASSED BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (CLASS_ID) REFERENCES CLASS(CLASS_ID)
);

INSERT INTO STUDENT (STUDENT_ID,PASSWORD,NAME,EMAIL,SEMESTER) VALUES
	('ice1','abc123','Rory Williams','ice1@uniwa.gr',1),
    ('ice2','11051989','Amy Pond','ice2@uniwa.gr',5),
    ('ice3','WaSDANdLOL','Tim Smith','ice3@uniwa.gr',7);

INSERT INTO CLASS (COURSE, CLASS_ID, SEMESTER, PERIOD, ECTS, UNITS, HOURS, ORIENTATION, COURSE_TYPE) VALUES
    ('MATHEMATICAL ANALYSIS I', 'ICE1-1001', '1', 'F', '5', '5', '5', 'M', 'MANDATORY'),
    ('LINEAR ALGEBRA', 'ICE1-1002', '1', 'F', '4', '4', '4', 'M', 'MANDATORY'),
    ('INTRODUCTION TO COMPUTER SCIENCE', 'ICE1-1003', '1', 'F', '5', '5', '5', 'M', 'MANDATORY'),
    ('COMPUTER PROGRAMMING', 'ICE1-1004', '1', 'F', '6', '6', '6', 'M', 'MANDATORY'),
    ('DISCRIMINATE MATHEMATICS', 'ICE1-1005', '1', 'F', '5', '4', '4', 'M', 'MANDATORY'),
    ('PHYSICS', 'ICE1-1006', '1', 'F', '5', '4', '4', 'M', 'MANDATORY'),
    ('DESIGN AND ANALYSIS OF ALGORITHMS', 'ICE1-2001', '2', 'S', '5', '4', '4', 'M', 'MANDATORY'),
    ('PROBABILITY AND STATISTICS', 'ICE1-2002', '2', 'S', '4', '4', '4', 'M', 'MANDATORY'),
    ('MATHEMATICAL ANALYSIS II', 'ICE1-2003', '2', 'S', '5', '4', '4', 'M', 'MANDATORY'),
    ('OBJECT-ORIENTED PROGRAMMING', 'ICE1-2004', '2', 'S', '6', '6', '6', 'M', 'MANDATORY'),
    ('DIGITAL DESIGN', 'ICE1-2005', '2', 'S', '5', '4', '4', 'M', 'MANDATORY'),
    ('CIRCUIT THEORY', 'ICE1-2006', '2', 'S', '5', '6', '6', 'M', 'MANDATORY'),
    ('ALGORITHMS AND COMPLEXITY', 'ICE1-3001', '3', 'F', '5', '4', '4', 'M', 'MANDATORY'),
    ('ELECTRONICS', 'ICE1-3002', '3', 'F', '5', '5', '5', 'M', 'MANDATORY'),
    ('DATA STRUCTURES', 'ICE1-3003', '3', 'F', '5', '5', '5', 'M', 'MANDATORY'),
    ('COMPUTER NETWORKS I', 'ICE1-3004', '3', 'F', '5', '4', '4', 'M', 'MANDATORY'),
    ('OPERATIONAL SYSTEMS I', 'ICE1-3005', '3', 'F', '5', '4', '4', 'M', 'MANDATORY'),
    ('COMPUTER ARCHITECTURE', 'ICE1-3006', '3', 'F', '5', '5', '5', 'M', 'MANDATORY'),
    ('DATABASES I', 'ICE1-4001', '4', 'S', '5', '4', '4', 'M', 'MANDATORY'),
    ('NETWORKS COMPUTERS II', 'ICE1-4002', '4', 'S', '4', '4', '4', 'M', 'MANDATORY'),
    ('OPERATING SYSTEMS II', 'ICE1-4003', '4', 'S', '4', '4', '4', 'M', 'MANDATORY'),
    ('APPLICATION DEVELOPMENT METHODOLOGIES', 'ICE1-4004', '4', 'S', '5', '5', '5', 'M', 'MANDATORY'),
    ('DIGITAL SYSTEMS DESIGN', 'ICE1-4005', '4', 'S', '5', '4', '4', 'M', 'MANDATORY'),
    ('SIGNALS AND SYSTEMS', 'ICE1-4006', '4', 'S', '5', '4', '4', 'M', 'MANDATORY'),
    ('TECHNICAL TEXT SYNTAX', 'ICE1-4007', '4', 'S', '2', '3', '3', 'M', 'MANDATORY'),
    ('DATABASES II', 'ICE1-5001', '5', 'F', '5', '4', '4', 'M', 'MANDATORY'),
    ('NETWORK PROGRAMMING', 'ICE1-5002', '5', 'F', '5', '5', '5', 'M', 'MANDATORY'),
    ('ANALYSIS AND DESIGN OF INFORMATION SYSTEMS', 'ICE1-5003', '5', 'F', '5', '5', '5', 'M', 'MANDATORY'),
    ('ARTIFICIAL INTELLIGENCE', 'ICE1-5004', '5', 'F', '5', '4', '4', 'M', 'MANDATORY'),
    ('DIGITAL SIGNAL PROCESSING', 'ICE1-5005', '5', 'F', '5', '4', '4', 'M', 'MANDATORY'),
    ('INTRODUCTION TO PARALLEL COMPUTING', 'ICE1-5006', '5', 'F', '5', '4', '4', 'M', 'MANDATORY'),
    ('SOFTWARE TECHNOLOGY', 'ICE1-6001', '6', 'S', '5', '4', '4', 'M', 'MANDATORY'),
    ('SECURITY IN INFORMATION TECHNOLOGY', 'ICE1-6002', '6', 'S', '5', '4', '4', 'M', 'MANDATORY'),
    ('COMPILERS', 'ICE1-6003', '6', 'S', '5', '4', '4', 'M', 'MANDATORY'),
    ('MICROELECTRONICS', 'ICE1-6004', '6', 'S', '5', '4', '4', 'M', 'MANDATORY'),
    ('DISTRIBUTED SYSTEMS', 'ICE1-6005', '6', 'S', '5', '4', '4', 'M', 'MANDATORY'),
    ('DIGITAL COMMUNICATIONS', 'ICE1-6006', '6', 'S', '5', '4', '4', 'M', 'MANDATORY'),
    ('COMPUTER SYSTEMS TECHNOLOGY', 'ICE1-7001', '7', 'F', '5', '4', '4', 'M', 'MANDATORY'),
    ('THEORY OF COMPUTATION', 'ICE1-7002', '7', 'F', '5', '4', '4', 'M', 'MANDATORY'),
    ('DESIGN AND DEVELOPMENT OF INFORMATION SYSTEMS', 'ICE1-7101', '7', 'F', '5', '5', '5', 'MS', 'MANDATORY'),
    ('INFORMATION RETRIEVAL', 'ICE1-7102', '7', 'F', '5', '4', '4', 'MS', 'MANDATORY'),
    ('PATTERN RECOGNITION AND MACHINE LEARNING', 'ICE1-7103', '7', 'F', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('KNOWLEDGE MANAGEMENT', 'ICE1-7104', '7', 'F', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('SPECIAL TOPICS IN SOFTWARE TECHNOLOGY', 'ICE1-7105', '7', 'F', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('DATA MINING', 'ICE1-7106', '7', 'F', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('IMAGE PROCESSING', 'ICE1-7107', '7', 'F', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('OPERATIONS RESEARCH', 'ICE1-7108', '7', 'F', '5', '5', '5', 'ES', 'ELECTIVE'),
    ('CONSTRAINT MODELING AND PROGRAMMING', 'ICE1-7109', '7', 'F', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('MANAGEMENT INFORMATION SYSTEMS', 'ICE1-7110', '7', 'F', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('HEALTH INFORMATICS', 'ICE1-7111', '7', 'F', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('SOFTWARE QUALITY AND RELIABILITY', 'ICE1-7112', '7', 'F', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('SYSTEMS DECISION AND PROCESS MANAGEMENT', 'ICE1-7113', '7', 'F', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('FUZZY LOGIC AND UNCERTAINTY SYSTEMS', 'ICE1-7114', '7', 'F', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('MICROCOMPUTERS', 'ICE1-7201', '7', 'F', '5', '4', '4', 'MH', 'MANDATORY'),
    ('COMPUTER-AID SYSTEMS DESIGN', 'ICE1-7202', '7', 'F', '5', '4', '4', 'MH', 'MANDATORY'),
    ('BIOMECHANICAL COMPUTING', 'ICE1-111', '7', 'F', '5', '4', '4', 'EH', 'ELECTIVE'),
    ('INDUSTRIAL COMPUTER COMPUTER COMPUTING', 'ICE1-7203', '7', 'F', '5', '4', '4', 'EH', 'ELECTIVE'),
    ('EMBEDDED SYSTEMS', 'ICE1-7204', '7', 'F', '5', '4', '4', 'EH', 'ELECTIVE'),
    ('INTEGRATED CIRCUITS FOR SPECIALIZED APPLICATIONS', 'ICE1-7205', '7', 'F', '5', '4', '4', 'EH', 'ELECTIVE'),
    ('PARALLEL SYSTEMS', 'ICE1-7206', '7', 'F', '5', '4', '4', 'EH', 'ELECTIVE'),
    ('ROBOTICS', 'ICE1-7207', '7', 'F', '5', '4', '4', 'EH', 'ELECTIVE'),
    ('VLSI DESIGN', 'ICE1-7208', '7', 'F', '5', '4', '4', 'EH', 'ELECTIVE'),
    ('HIGH RELIABILITY COMPUTER SYSTEMS', 'ICE1-7209', '7', 'F', '5', '4', '4', 'EH', 'ELECTIVE'),
    ('ADVANCED NETWORK TECHNOLOGIES', 'ICE1-7301', '7', 'F', '5', '4', '4', 'MN', 'MANDATORY'),
    ('NETWORK AND COMMUNICATIONS SECURITY', 'ICE1-7302', '7', 'F', '5', '4', '4', 'MN', 'MANDATORY'),
    ('OPTIMIZATION', 'ICE1-7303', '7', 'F', '5', '4', '4', 'EN', 'ELECTIVE'),
    ('INTERNET OF SUBJECTS', 'ICE1-7304', '7', 'F', '5', '4', '4', 'EN', 'ELECTIVE'),
    ('OPTICAL COMMUNICATIONS NETWORKS', 'ICE1-7305', '7', 'F', '5', '4', '4', 'EN', 'ELECTIVE'),
    ('REGULATORY FRAMEWORK FOR COMMUNICATIONS AND INFORMATION SECURITY', 'ICE1-7306', '7', 'F', '5', '4', '4', 'EN', 'ELECTIVE'),
    ('CRYPTOGRAPHY', 'ICE1-7307', '7', 'F', '5', '4', '4', 'EN', 'ELECTIVE'),
    ('TELECOMMUNICATION SYSTEMS', 'ICE1-7308', '7', 'F', '5', '4', '4', 'EN', 'ELECTIVE'),
    ('PROJECT MANAGEMENT', 'ICE1-7401', '7', 'F', '5', '4', '4', 'EG', 'ELECTIVE'),
    ('EDUCATIONAL TECHNOLOGY & INFORMATION TECHNOLOGY DIDACTICS', 'ICE1-7402', '7', 'F', '5', '4', '4', 'EG', 'ELECTIVE'),
    ('HISTORY OF TECHNOLOGY', 'ICE1-7403', '7', 'F', '5', '4', '4', 'EG', 'ELECTIVE'),
    ('LAW AND CYBERETHICS', 'ICE1-7404', '7', 'F', '5', '4', '4', 'EG', 'ELECTIVE'),
    ('HUMAN-COMPUTER INTERACTION', 'ICE1-8101', '8', 'S', '5', '4', '4', 'MS', 'MANDATORY'),
    ('COMPUTER GRAPHICS', 'ICE1-8102', '8', 'S', '5', '4', '4', 'MS', 'MANDATORY'),
    ('LARGE-SCALE DATA MANAGEMENT', 'ICE1-8103', '8', 'S', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('NATURAL LANGUAGE PROCESSING AND SEMANTIC WEB', 'ICE1-8104', '8', 'S', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('INTELLIGENT SYSTEMS & DECISION SUPPORT SYSTEMS', 'ICE1-8105', '8', 'S', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('ELECTRONICS LEARNING', 'ICE1-8106', '8', 'S', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('E-COMMERCE - ENTREPRENEURSHIP', 'ICE1-8107', '8', 'S', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('GRAPH THEORY AND APPLICATIONS', 'ICE1-8108', '8', 'S', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('GAME THEORY', 'ICE1-8109', '8', 'S', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('NEURAL NETWORKS', 'ICE1-8110', '8', 'S', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('COMPUTER VISION', 'ICE1-8111', '8', 'S', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('DESIGN OF GAMES & VIRTUAL & AUGMENTED REALITY APPLICATIONS', 'ICE1-8112', '8', 'S', '5', '4', '4', 'ES', 'ELECTIVE'),
    ('AUTOMATIC SYSTEMS CONTROL', 'ICE1-8201', '8', 'S', '5', '4', '4', 'MH', 'MANDATORY'),
    ('ADVANCED COMPUTER ARCHITECTURE', 'ICE1-8202', '8', 'S', '5', '4', '4', 'MH', 'MANDATORY'),
    ('HARDWARE SECURITY AND RELIABILITY', 'ICE1-8203', '8', 'S', '5', '4', '4', 'EH', 'ELECTIVE'),
    ('MECHATRONICS', 'ICE1-8204', '8', 'S', '5', '4', '4', 'EH', 'ELECTIVE'),
    ('ADVANCED DESIGN AND SYNTHESIS OF DIGITAL SYSTEMS', 'ICE1-8205', '8', 'S', '5', '4', '4', 'EH', 'ELECTIVE'),
    ('STOCKISTIC AND NON-LINEAR SYSTEMS', 'ICE1-8206', '8', 'S', '5', '4', '4', 'EH', 'ELECTIVE'),
    ('DIGITAL SYSTEMS CONTROL', 'ICE1-8207', '8', 'S', '5', '4', '4', 'EH', 'ELECTIVE'),
    ('MOBILE COMMUNICATION NETWORKS', 'ICE1-8301', '8', 'S', '5', '4', '4', 'MN', 'MANDATORY'),
    ('CLOUD COMPUTING AND SERVICES', 'ICE1-8302', '8', 'S', '5', '4', '4', 'MN', 'MANDATORY'),
    ('WIRELESS SENSOR NETWORKS', 'ICE1-8303', '8', 'S', '5', '4', '4', 'EN', 'ELECTIVE'),
    ('SOFTWARE-DEFINED NETWORKING', 'ICE1-8304', '8', 'S', '5', '4', '4', 'EN', 'ELECTIVE'),
    ('BROADBAND NETWORKS', 'ICE1-8305', '8', 'S', '5', '4', '4', 'EN', 'ELECTIVE'),
    ('MULTIMEDIA AND MULTIMEDIA COMMUNICATIONS', 'ICE1-8306', '8', 'S', '5', '4', '4', 'EN', 'ELECTIVE'),
    ('MOBILE DEVICE TECHNOLOGY AND PROGRAMMING', 'ICE1-8307', '8', 'S', '5', '4', '4', 'EN', 'ELECTIVE'),
    ('INFORMATION AND SOCIETY - TECHNOLOGY OF EXPRESSION', 'ICE1-8401', '8', 'S', '5', '4', '4', 'EG', 'ELECTIVE'),
    ('PHILOSOPHY OF INFORMATIVE AND MODERN ICT APPLICATIONS', 'ICE1-8402', '8', 'S', '5', '4', '4', 'EG', 'ELECTIVE'),
    ('THESIS', 'ICE1-9010', '10', 'B', '30', '0', '0', 'M', 'MANDATORY'),
    ('PRACTICAL PRACTICE', 'ICE1-9020', '9', 'B', '5', '0', '0', 'EG', 'ELECTIVE');

INSERT INTO GRADE (STUDENT_ID, CLASS_ID)
SELECT
    S.STUDENT_ID,
    C.CLASS_ID
FROM
    STUDENT AS S
CROSS JOIN
    CLASS AS C;
    
UPDATE GRADE g
JOIN (
    SELECT 
        STUDENT_ID, 
        CLASS_ID,
        ROUND(RAND() * 10, 1) AS NEW_GRADE
    FROM GRADE
) AS rand_grades
ON g.STUDENT_ID = rand_grades.STUDENT_ID AND g.CLASS_ID = rand_grades.CLASS_ID
SET 
    g.GRADE = rand_grades.NEW_GRADE,
    g.PASSED = rand_grades.NEW_GRADE >= 5.0;

SELECT * FROM GRADE;